config/routes.rb
Tables::Application.routes.draw do

  resources :joins

  resources :key_records

  get "home/index"

  resources :data_sets do
  	resources :fields
  	resources :records do
  		resources :cells
		end
  	resources :keys do
			member do 
				get 'find_records'
			end
  		resources :key_fields
  		resources :conditions
		end
	end

  root :to => 'home#index'

end

app/models/data_set.rb
class DataSet < ActiveRecord::Base
  attr_accessible :checksum, :name, :parameters, :source
	has_many :records
	has_many :fields
	has_many :keys, :as => :keyable
end

app/controllers/data_sets_controller.rb
class DataSetsController < ApplicationController

	# GET /data_sets/1
	# GET /data_sets/1.json
	def show
		@jquery = InitHelper.new( gon )

		# load the target dataset
		@data_set = DataSet.find(params[:id])

		# get the other revisions of this table
		@revisions = []
		DataSet.where( :name => @data_set.name, :parameters => @data_set.parameters ).order( "created_at DESC" ).each do |revision|
			if revision.id != @data_set.id
				@revisions << revision
			end
		end
		
		gon.table = Table.new( @data_set ) # this is for the initial load
		respond_to do |format|
			format.json { render json: gon.table } 
			format.html # show.html.erb
		end
	end

	# GET /data_sets
	# GET /data_sets.json
	def index
		@jquery = InitHelper.new( gon )
		@data_sets = DataSet.all

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @data_sets }
		end
	end


	# GET /data_sets/new
	# GET /data_sets/new.json
	def new
		@data_set = DataSet.new

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @data_set }
		end
	end

	# GET /data_sets/1/edit
	def edit
		@data_set = DataSet.find(params[:id])
	end

	# POST /data_sets
	# POST /data_sets.json
	def create
		@data_set = DataSet.new(params[:data_set])

		respond_to do |format|
			if @data_set.save
				format.html { redirect_to @data_set, notice: 'Data set was successfully created.' }
				format.json { render json: @data_set, status: :created, location: @data_set }
			else
				format.html { render action: "new" }
				format.json { render json: @data_set.errors, status: :unprocessable_entity }
			end
		end
	end

	# PUT /data_sets/1
	# PUT /data_sets/1.json
	def update
		@data_set = DataSet.find(params[:id])

		respond_to do |format|
			if @data_set.update_attributes(params[:data_set])
				format.html { redirect_to @data_set, notice: 'Data set was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @data_set.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /data_sets/1
	# DELETE /data_sets/1.json
	def destroy
		@data_set = DataSet.find(params[:id])
		@data_set.destroy

		respond_to do |format|
			format.html { redirect_to data_sets_url }
			format.json { head :no_content }
		end
	end
end

app/helpers/data_sets_helper.rb
module DataSetsHelper
end

app/views/data_sets/_data_set.html.erb
  <tr>
    <td><%= data_set.name %></td>
    <td><%= data_set.parameters %></td>
    <td><%= data_set.checksum %></td>
    <td><%= data_set.source %></td>
    <td><%= link_to 'Show', data_set %></td>
    <td><%= link_to 'Edit', edit_data_set_path(data_set) %></td>
    <td><%= link_to 'Destroy', data_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

app/views/data_sets/_footer.html.erb
	</tbody>
</table>

app/views/data_sets/_form.html.erb
<%= form_for(@data_set) do |f| %>
  <% if @data_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_set.errors.count, "error") %> prohibited this data_set from being saved:</h2>

      <ul>
      <% @data_set.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parameters %><br />
    <%= f.text_field :parameters %>
  </div>
  <div class="field">
    <%= f.label :checksum %><br />
    <%= f.text_field :checksum %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data_sets/_full_display.html.erb
<% revision ||= nil # optionally support key filtering %>
<% key ||= nil # optionally support key filtering %>
<% valid ||= true # when conditions are passed, do we return matching or non matching %>
<% primary = revision || data_set %>
<% table_id ||= "data_set_#{primary.id}" %>

<% if revision.nil? && key.nil? %>
	<b>Name: </b><%= "#{data_set.name} #{data_set.parameters.nil? ? '' : "<b>Parameters:</b> #{data_set.parameters}" }" %><br />
	<b>Created At:</b> <%= data_set.created_at %><br />
<% elsif ! key.nil? # no title%>

<% else # revision %>
	<% revision_title = "#{revision.created_at} - #{revision.created_at < data_set.created_at ? 'Earlier' : 'Later'}" %> 
	<h3>Revision: <%= revision_title %></h3> 
<% end %>


<div style="height:auto;min-height:250px" >
	<% source_url = data_set_url( primary, :format => "json" ) %>
	<table <%= "data-source=#{source_url}" %>  <%= @jquery.set_id( table_id, :data_table ) %> class="display" >
		<thead>
			<tr>
				<% primary.fields.each do |field| %>
					<th><%= field.name %></th>
				<% end %>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>

</div>

app/views/data_sets/_header.html.erb
<h1>Listing data_sets</h1>
<table <%= @jquery.set_id("data_sets_table", :data_table ) %> class="display" >
	<thead>
  <tr>
    <th>Name</th>
    <th>Parameters</th>
    <th>Checksum</th>
    <th>Source</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
	</thead>
	<tbody>

app/views/data_sets/create.js.erb
console.log("holy shit i made it");

app/views/data_sets/data_set.js.erb
$('#example').dataTable( {
				"aaData": [
				/* Reduced data set */
<% @data_set.records.each do |record| %>
			[ 
				[ "Trident", "Internet Explorer 4.0", "Win 95+", 4, "X" ],
				[ "Trident", "Internet Explorer 5.0", "Win 95+", 5, "C" ],
				[ "Trident", "Internet Explorer 5.5", "Win 95+", 5.5, "A" ],
				[ "Trident", "Internet Explorer 6.0", "Win 98+", 6, "A" ],
				[ "Trident", "Internet Explorer 7.0", "Win XP SP2+", 7, "A" ],
				[ "Gecko", "Firefox 1.5", "Win 98+ / OSX.2+", 1.8, "A" ],
				[ "Gecko", "Firefox 2", "Win 98+ / OSX.2+", 1.8, "A" ],
				[ "Gecko", "Firefox 3", "Win 2k+ / OSX.3+", 1.9, "A" ],
				[ "Webkit", "Safari 1.2", "OSX.3", 125.5, "A" ],
				[ "Webkit", "Safari 1.3", "OSX.3", 312.8, "A" ],
				[ "Webkit", "Safari 2.0", "OSX.4+", 419.3, "A" ],
				[ "Webkit", "Safari 3.0", "OSX.4+", 522.1, "A" ]
<% end %>
				],
				"aoColumns": [
			{ "sTitle": "Engine" },
				{ "sTitle": "Browser" },
				{ "sTitle": "Platform" },
				{ "sTitle": "Version", "sClass": "center" },
				{
					"sTitle": "Grade",
					"sClass": "center",
					"fnRender": function(obj) {
						var sReturn = obj.aData[ obj.iDataColumn ];
						if ( sReturn == "A" ) {
							sReturn = "<b>A</b>";
						}
						return sReturn;
					}
				}
			]
			} );	
		);
	);  

app/views/data_sets/edit.html.erb
<h1>Editing data_set</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_set %> |
<%= link_to 'Back', data_sets_path %>

app/views/data_sets/index.html.erb
<%= link_to "Only Head Revisions", data_sets_url(:filter => 'head'), :remote => true, :class => 'show_datasets' %><br />
<%= link_to "All Revisions", data_sets_url(), :remote => true, :class => 'show_datasets' %><br />
<script>
	$('.show_datasets').bind('ajax:success', function(event, xhr, status, data) {  
		var table = JSON.parse( data.responseText );
		setMainDisplay( table );
	} );
</script>
<div id="data_sets">
	<%= render 'data_sets/header' %>
	<%= render @data_sets %>
	<%= render 'data_sets/footer' %>
</div>

<br />

app/views/data_sets/new.html.erb
<h1>New data_set</h1>

<%= render 'form' %>

<%= link_to 'Back', data_sets_path %>

app/views/data_sets/show.html.erb
<%= link_to 'Show All Data Sets', data_sets_path %>

<p id="notice"><%= notice %></p>
<div>
	<%= link_to "Show Full Dataset", data_set_url(@data_set), :remote => true, :class => 'reset_main_display' %><br />
	<script>
		$('.reset_main_display').bind('ajax:success', function(event, xhr, status, data) {  
			var table = JSON.parse(data.responseText);
			setMainDisplay( table );
		} );
	</script>
	<div id="main_display_title" ></div>
	<table id="main_display" class="display" ></table>
</div>
<br />

<div <%= @jquery.set_id( "data_set_tabs", :tabs ) %> style="height:auto;min-height:100px" >
	<ul>
		<li><a href="#key_tabs">Keys</a></li>
		<li><a href="#joins">Joins</a></li>
		<li><a href="#data_set_field_stats">Field Stats</a></li>
		<li><a href="#revisions">Revisions</a></li>
	</ul>

	<div <%= @jquery.set_id( "key_tabs", :tabs, 'active' => 0 ) %>  >
		<ul>
			<li><a href="#current_keys">Current</a></li>
			<li><a href="#create_key_tab">Create New</a></li>
		</ul>
		<div <%= @jquery.set_id( "current_keys", :accordion  ) %>  >
			<%= render @data_set.keys %>
		</div>
		<div id="create_key_tab" >
			<%= render 'keys/form', :keyable => @data_set %>
		</div>
	</div>

	<div <%= @jquery.set_id( "joins", :tabs, 'active' => 0 ) %>  >
		<ul>
			<li><a href="#current_joins">Current</a></li>
			<li><a href="#create_join">Create New</a></li>
		</ul>
		<div <%= @jquery.set_id( "current_joins", :accordion  ) %>  >
			<% @data_set.keys.each do |key| %>
				<%= render key.left_joins %>
				<%= render key.right_joins %>
			<% end %>
		</div>
		<div id="create_join" >
			<%= render 'joins/form', :data_set => @data_set %>
		</div>
	</div>

	<div <%= @jquery.set_id( "data_set_field_stats", :accordion  ) %>  >
		<% @data_set.fields.each do |field| %>
			<h3><%= field.name %></h3>
			<div id="<%= field.name %>_stats" style="height:auto;min-height:100px" >
				<ul>
					<li><b>Records With This Field:</b> <%= field.cells.size %></li>
					<% unique_cell_values = field.cells.map(&:string).uniq %>
					<li><b>Number of Unique Field Values:</b> <%= unique_cell_values.size %></li>
					<li><b>Unique Field Values:</b> <%= unique_cell_values %></li>
				</ul>
			</div>
		<% end %>
	</div>

	<div <%= @jquery.set_id( "revisions", :accordion ) %> style="height:auto" >
		<% @revisions.each do |revision| %>
			<%= render 'full_display', :data_set => @data_set, :revision => revision %>
		<% end %>
	</div>

</div>

app/views/data_sets/show.js.erb
$('#main_display_info').dataTable( {
	"aaData": <%= @table[ :records ].to_json %>,
	"aoColumns": <%= @table[ :columns ].to_json %>
} );	