config/routes.rb
Tables::Application.routes.draw do

  resources :joins

  resources :key_records

  get "home/index"

  resources :data_sets do
  	resources :fields
  	resources :records do
  		resources :cells
		end
  	resources :keys do
			member do 
				get 'find_records'
			end
  		resources :key_fields
  		resources :conditions
		end
	end

  root :to => 'home#index'

end

app/models/key.rb
class Key < ActiveRecord::Base
	belongs_to :keyable, :polymorphic => true
	attr_accessible :name

	has_many :key_fields, :dependent => :destroy
	has_many :fields, :through => :key_fields
	has_many :key_records, :dependent => :destroy
	has_many :records, :through => :key_records

	has_many :left_joins, :class_name => "Join", :foreign_key => "left_key_id"
	has_many :right_joins, :class_name => "Join", :foreign_key => "right_key_id"

	has_many :conditions, :dependent => :destroy

	def unique_field_names
		return self.fields.collect {|field| field.name }
	end

	def reindex_records

		self.key_records.each do |key_record|
			key_record.status = ''

			self.conditions.each do |condition|
				condition.valid_record?( key_record )
			end # end of conditions.each

			if key_record.status == ''
				key_record.status = 'valid'
			end

			key_record.save!

		end # end of key_record.each
	end

	def set_records
		self.keyable.records.each do |record| # check each record
			has_all_fields = true # does it have the requisite keys
			self.key_fields.each do |key_field|
				has_all_fields = false if record.get_cell( key_field.field ).field_id.nil?
			end
			if has_all_fields
				key_record = self.key_records.create
				key_record.record = record
				key_record.status = 'valid'
				key_record.save
			end
		end
	end

	def valid_records
		self.key_records.where( :status => 'valid' ).collect {|key_record| key_record.record }
	end

	def get_duplicate_records
		primary_keys = Hash.new	

		valid_records.each do |record| # check each record
			pk_value = ""
			self.key_fields.each do |key_field|
				pk_value << "[#{record.get_cell( key_field.field ).string}]"
			end
			primary_keys[ pk_value ] ||= Array.new
			primary_keys[ pk_value ] << record
		end

		duplicate_records = Array.new
		primary_keys.each do |key,records|
			duplicate_records.concat( records ) if records.size > 1	
		end
		duplicate_records	
	end

end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
	$key_index = 1 # what index in the main tab, todo: improve this

	# POST /keys
	# POST /keys.json
	def create
		@jquery = InitHelper.new( gon )
		if params[:data_set_id]
			@keyable = DataSet.find(params[:data_set_id])
		elsif params[:join_id]
			@keyable = Join.find(params[:join_id])
		else
			raise "missing keyable id"
		end

		if params[:field_ids].nil?
			raise "Must select fields when creating a key" 
		else
			@key = @keyable.keys.create(params[:key])
			params[:field_ids].each do |field_id|
				field = @keyable.fields.where( :id => field_id )
				key_field = @key.key_fields.create 
				key_field.field_id = field_id
				key_field.save!
			end
			@key.set_records # create a key_record's index

			respond_to do |format|
				format.json { render json: 
					{ 
						'key_id' => @key.id, 
						'html' => render_to_string( :partial =>"key.html.erb",:locals =>{:key=>@key} ), 
						'table' => KeyTable.new( @key, 'valid' ),
						'content_type' => 'text/json'
					} 
				}
			end
		end
	end

	# GET /keys/1
	# GET /keys/1.json
	def show
		if params[:data_set_id]
			@keyable = DataSet.find(params[:data_set_id])
		elsif params[:join_id]
			@keyable = Join.find(params[:join_id])
		else
			raise "missing keyable id"
		end
		@key = @keyable.keys.find(params[:id])

		records_type = params[:records_type] 
		table = KeyTable.new( @key, records_type )
		respond_to do |format|
			format.json { render json: 
				{ 
				  'table' => table,
					'content_type' => 'text/json'
				}
			} 
		end
	end

	# DELETE /keys/1
	# DELETE /keys/1.json
	def destroy
		@key = Key.find(params[:id])
		@key.destroy

		respond_to do |format|
			format.json { head :no_content }
		end
	end
end

app/helpers/keys_helper.rb
module KeysHelper
end

app/views/keys/_form.html.erb
<div id="create_key" >
	<%= form_for( [keyable, keyable.keys.build], :remote => true, :html => {:class => 'new_key_success'} ) do |f| %>
		<div class="field">
			<%= f.label :name %><br />
			<%= f.text_field :name %>
		</div>
		<ul>
			<% keyable.fields.each do |field| %>
				<li>
				<%= check_box_tag 'field_ids[]', field.id -%>
				<%= field.name -%>
				</li>
			<% end %>
		</ul>

		<div class="actions">
			<%= f.submit( "Create Key" ) %>
		</div>
	<% end %>

</div>

app/views/keys/_key.html.erb
<% uid = "key_#{key.id}" %>
<h3 id="<%= uid %>_header" ><%= key.name %></h3>
<div <%= @jquery.set_id( "#{uid}_tabs", :tabs ) %> style="height:auto;min-height:150px" >

	<ul>
		<li><a href="#<%= uid %>_basics">Basics</a></li>
		<li><a href="#<%= uid %>_conditions">Conditions</a></li>
		<li><a href="#<%= uid %>_add_condition">Add Condition</a></li>
	</ul>

	<div id="<%= uid %>_basics" >
		<b>Number Of Minimal Records:</b> <%= key.records.count %><br />
		<b>Key Field Names:</b> <%= key.unique_field_names.join( "," ) %><br />
		<b>Number of Conditions:</b> <%= key.conditions.count %><br />
		<b>Number Of Conditional Records:</b> <%= key.key_records.where( :status => 'valid' ).count %><br />
		<% ajax_class = "set_main_display" %>

		<h4>Analyze Key Records</h4>
		<%= link_to "Valid Key Records", data_set_key_url(key.keyable,key, :records_type => 'valid'), :remote => true, :class => ajax_class, :title => "Records meeting all conditions", :rel => "tooltip" %><br />
		<%= link_to "Show Records With Duplicate Key Fields", data_set_key_url(key.keyable,key, :records_type => 'duplicate' ), :remote => true, :class => ajax_class, :title => "Records that have overlapping values across all the key fields", :rel => "tooltip" %><br />

		<h4>Records Not Meeting Requirements of Key</h4>
		<%= link_to "Not Meeting Conditions", data_set_key_url(key.keyable,key, :records_type => 'invalid'), :remote => true, :class => ajax_class, :title => "Records NOT meeting all conditions", :rel => "tooltip" %><br />
		<%= link_to "Records Excluded From Key Candidates", data_set_key_url(key.keyable,key, :records_type => 'not' ), :remote => true, :class => ajax_class, :title => "Records that do not have all the fields for this key", :rel => "tooltip" %><br />

		<% ajax_class = "delete_key_#{uid}" %>
		<%= link_to 'Delete Key', data_set_key_url( key.keyable,key ), :method => :delete, :remote => true, :class => ajax_class %>
		<script>
			$('.<%= ajax_class %>').bind('ajax:success', function() {  
				$('#<%= uid %>').fadeOut();  
				$('#<%= uid %>_header').fadeOut();  
				resetJQueryUI('accordion','current_keys');
			});
		</script>
	</div>
	<div id="<%= uid %>_conditions" >
		<%= render key.conditions %>
	</div>
	<div id="<%= uid %>_add_condition" >
		<%= render 'conditions/form.html.erb', :key => key  %>
	</div>
</div>

app/views/keys/edit.html.erb
<h1>Editing key</h1>

<%= render 'form' %>

<%= link_to 'Show', @key %> |
<%= link_to 'Back', keys_path %>

app/views/keys/index.html.erb
<h1>Listing keys</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Data set</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @keys.each do |key| %>
  <tr>
    <td><%= key.name %></td>
    <td><%= key.data_set %></td>
    <td><%= link_to 'Show', key %></td>
    <td><%= link_to 'Edit', edit_key_path(key) %></td>
    <td><%= link_to 'Destroy', key, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Key', new_key_path %>

app/views/keys/new.html.erb
<h1>New key</h1>

<%= render 'form' %>

<%= link_to 'Back', keys_path %>

app/views/keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @key.name %>
</p>

<p>
  <b>Data set:</b>
  <%= @key.data_set %>
</p>


<%= link_to 'Edit', edit_key_path(@key) %> |
<%= link_to 'Back', keys_path %>