config/routes.rb
Tables::Application.routes.draw do

  resources :joins

  resources :key_records

  get "home/index"

  resources :data_sets do
  	resources :fields
  	resources :records do
  		resources :cells
		end
  	resources :keys do
			member do 
				get 'find_records'
			end
  		resources :key_fields
  		resources :conditions
		end
	end

  root :to => 'home#index'

end

app/models/cell.rb
class Cell < ActiveRecord::Base
  belongs_to :record
  belongs_to :field
  attr_accessible :datetime, :float, :int, :string

	def set_to_type( type )
		case type
		when 'datetime'
			self.datetime = self.string
		when 'float'
			return false unless self.string =~ /^\d*\.?\d+$/
			self.float = self.string
		when 'int'
			return false unless self.string =~ /^\d+$/
			self.int = self.string
		end
		return self.save
	end

end

app/controllers/cells_controller.rb
class CellsController < ApplicationController
  # GET /cells
  # GET /cells.json
  def index
    @cells = Cell.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cells }
    end
  end

  # GET /cells/1
  # GET /cells/1.json
  def show
    @cell = Cell.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cell }
    end
  end

  # GET /cells/new
  # GET /cells/new.json
  def new
    @cell = Cell.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cell }
    end
  end

  # GET /cells/1/edit
  def edit
    @cell = Cell.find(params[:id])
  end

  # POST /cells
  # POST /cells.json
  def create
    @cell = Cell.new(params[:cell])

    respond_to do |format|
      if @cell.save
        format.html { redirect_to @cell, notice: 'Cell was successfully created.' }
        format.json { render json: @cell, status: :created, location: @cell }
      else
        format.html { render action: "new" }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cells/1
  # PUT /cells/1.json
  def update
    @cell = Cell.find(params[:id])

    respond_to do |format|
      if @cell.update_attributes(params[:cell])
        format.html { redirect_to @cell, notice: 'Cell was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cells/1
  # DELETE /cells/1.json
  def destroy
    @cell = Cell.find(params[:id])
    @cell.destroy

    respond_to do |format|
      format.html { redirect_to cells_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cells_helper.rb
module CellsHelper
end

app/views/cells/_form.html.erb
<%= form_for(@cell) do |f| %>
  <% if @cell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cell.errors.count, "error") %> prohibited this cell from being saved:</h2>

      <ul>
      <% @cell.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :record %><br />
    <%= f.text_field :record %>
  </div>
  <div class="field">
    <%= f.label :field %><br />
    <%= f.text_field :field %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :datetime %><br />
    <%= f.datetime_select :datetime %>
  </div>
  <div class="field">
    <%= f.label :int %><br />
    <%= f.text_field :int %>
  </div>
  <div class="field">
    <%= f.label :float %><br />
    <%= f.text_field :float %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cells/edit.html.erb
<h1>Editing cell</h1>

<%= render 'form' %>

<%= link_to 'Show', @cell %> |
<%= link_to 'Back', cells_path %>

app/views/cells/index.html.erb
<h1>Listing cells</h1>

<table>
  <tr>
    <th>Record</th>
    <th>Field</th>
    <th>String</th>
    <th>Datetime</th>
    <th>Int</th>
    <th>Float</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cells.each do |cell| %>
  <tr>
    <td><%= cell.record %></td>
    <td><%= cell.field %></td>
    <td><%= cell.string %></td>
    <td><%= cell.datetime %></td>
    <td><%= cell.int %></td>
    <td><%= cell.float %></td>
    <td><%= link_to 'Show', cell %></td>
    <td><%= link_to 'Edit', edit_cell_path(cell) %></td>
    <td><%= link_to 'Destroy', cell, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cell', new_cell_path %>

app/views/cells/new.html.erb
<h1>New cell</h1>

<%= render 'form' %>

<%= link_to 'Back', cells_path %>

app/views/cells/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Record:</b>
  <%= @cell.record %>
</p>

<p>
  <b>Field:</b>
  <%= @cell.field %>
</p>

<p>
  <b>String:</b>
  <%= @cell.string %>
</p>

<p>
  <b>Datetime:</b>
  <%= @cell.datetime %>
</p>

<p>
  <b>Int:</b>
  <%= @cell.int %>
</p>

<p>
  <b>Float:</b>
  <%= @cell.float %>
</p>


<%= link_to 'Edit', edit_cell_path(@cell) %> |
<%= link_to 'Back', cells_path %>